### PR TITLE
Update icons for better visual consistency

### PR DESCRIPTION
**Pull request by FStop**
See #95

### CODE REVIEW

**Comment by goldenapples** [comment]
Is this ready for merge?

**Comment by FStop** [comment]
@goldenapples nope not yet. Waiting for @danielbachhuber to wrap up adding some more shortcodes, then a few more tweaks.

**Comment by danielbachhuber** [comment]
@FStop feel free to finish this one up

**Comment by FStop** [comment]
@goldenapples this is ready for #reviewmerge

**Comment by goldenapples** [comment]
Looks nice!

**Pull request merged**
