### PR TITLE
Added "wordpress-plugin" type on composer.json

### PR DESCRIPTION
**Pull request by jimmyandrade**
Adding some more information so it's recognized as a WordPress Plugin.
More info on: https://roots.io/wordpress-plugins-with-composer/

### CODE REVIEW

**Comment by jimmyandrade** [comment]
@danielbachhuber what about this little PR?

**Comment by danielbachhuber** [comment]
@jimmyandrade Can you merge master? That'll fix the build failure.

**Comment by jimmyandrade** [comment]
@danielbachhuber So far, I haven't found a way to merge the branch (still don't understand some Git stuff). I think we better close this PR and open another, ok?

**Comment by danielbachhuber** [comment]
Works for me

**Pull request closed without merging**
